parameters:
    version: '0.1.0'

services:
    _defaults:
        bind:
            PoP\Translation\Contracts\TranslationAPIInterface: '@translation_api'
            PoP\FieldQuery\Schema\FeedbackMessageStoreInterface: '@feedback_message_store'
            PoP\QueryParsing\Parsers\QueryParserInterface: '@query_parser'

    feedback_message_store:
        class: \PoP\FieldQuery\Query\FeedbackMessageStore
        public: true
