parameters:
    version: '0.1.0'

services:
    _defaults:
        bind:
            PoP\Translation\TranslationAPIInterface: '@translation_api'
            PoP\FieldQuery\Schema\FeedbackMessageStoreInterface: '@feedback_message_store'
            PoP\QueryParsing\QueryParserInterface: '@query_parser'

    feedback_message_store:
        class: \PoP\FieldQuery\FeedbackMessageStore
        public: true
